### ISSUE TITLE
Using Place Building with no building selected and building count on causes crash

### ISSUE THREAD

**Issue by AgmasGold** [AgmasGold/anno-designer#11]
**Description**
If using the place building button before first selecting a building from the menu, and the Building Count option is checked under "Manage Stats", the program crashes.

**Steps to Reproduce**:
- open the program
- click "Place Building"
- click into the grid

**Workaround:**
1) Make sure a building is selected (via double click) from the menu before using the place building button.
**or**
2) Disable the Building Count option under the "Manage Stats" menu

Following a bug report from a user, we know what is causing this bug and we should be able to fix for the next release.

**Comment by FroggieFrog** [comment]
I think this was fixed with commit ec3e1d107fea217afea09310132a08c73c65059b.

**Comment by AgmasGold** [comment]
Yep - closing this issue.

**Comment by BiddinWar** [comment]
Should reopen this most likely, I'm getting this crash as of right now. 
Workarounds do still work though.

**Comment by AgmasGold** [comment]
Okay, thanks for the info, we'll do some investigating.

**Comment by AgmasGold** [comment]
> 
> 
> Should reopen this most likely, I'm getting this crash as of right now.
> Workarounds do still work though.

Do you have an error you could supply? There should be an error-log.txt file in the installation directory.

**Comment by AgmasGold** [comment]
Temporarily forgot - we haven't released this fix yet - it will be present in the next version. Closing this issue.
