### ISSUE TITLE
Filter building presets by selected game

### ISSUE THREAD

**Issue by auipga** [AgmasGold/anno-designer#113]
Searching (#31) a specific building (e.g. fire station) results in multiple results for all Anno versions.
It would be nice to preselect a version (e.g. 1800) and see only those buildings (also removing the upper level "(A7) 1800").
Preselection by tabs (preferred), radio, combobox or [multiple buttons in a row](https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons).
Then also save the selection in the .ad file.

**Comment by FroggieFrog** [comment]
I created some mockups. So please vote/comment which would be your favourite or even add another solution.

To achieve the solution with a `TabControl` we probably would need multiple `TreeViews`. I don't know what the performance would be. Also I think there is a significant amount of refactoring needed for the data loading of the `TreeView`.
And also I don't think we have much control of the order of the tabs.

1. with `Radiobuttons`
![mockup_Radiobutton](https://user-images.githubusercontent.com/6222752/59907959-90b7e500-940c-11e9-8c7c-d82bb3800ca2.png)

2. with `ComboBox`
![mockup_combobox](https://user-images.githubusercontent.com/6222752/59907968-97465c80-940c-11e9-85ae-1140a4b2a0d7.png)

Maybe it would be better to add `CheckBoxes` to the entries in the `ComboBox` to make the selection/deselection experience better.

3. with `TabControl`
![mockup_tab](https://user-images.githubusercontent.com/6222752/59907973-a0372e00-940c-11e9-944c-96e76e8fa33b.png)

**Comment by StingMcRay** [comment]
for the upper level (A7) Anno 1800, is made because it keeps the Anno's separated and in order of versions
 understand that some users not like the preset menu with all anno's showed but you must know that we picked-up the dev for this tool as the tool was only made for 1 Anno version at the time...
@FroggieFrog : Nice, i prefer the `ComboBox` Methode

**Comment by auipga** [comment]
@FroggieFrog your response time in incredible :)
I'd prefer ComboBox, then Radiobuttons. Both will work. Multi-line TabControls will jump around I think.

Thinking a bit further: Do we need to switch Anno versions or even use multiple in a single layout file? I guess not. It could therefore be enough to add `File > New Anno 1404`, `File > New Anno 1800` and so on to the main menu.

**Comment by FroggieFrog** [comment]
I would not add different menu items for different versions of the game.
This just adds some clutter to the UI and potentially confuses the user.

I prefer a combobox with checkboxes. See [Xceed CheckComboBox](https://github.com/xceedsoftware/wpftoolkit/wiki/CheckComboBox) for an example.

**Comment by StingMcRay** [comment]
@FroggieFrog : The `CheckComboBox` looks very nice however, then you still can select multiple Anno's right? I think a normal `ComboBox` is the best way to a choice for all, or 1 version ad the time is better.

To answer the question from @auipga
Q:  'Do we need to switch Anno versions or even use multiple in a single layout file?'
A: No, we do not use multiple anno's in a Single Layout, the preset was made so the program could be used for all anno's to make a layout for that anno version
About switching anno's, that depends if the value is be gone saved on the Window State Valeu's

**Comment by FroggieFrog** [comment]
Ok, my thinking was to support multiple games in a layout.
If there is a wish to support only 1 game in a layout, that will be a breaking change.

Maybe in a first step add the `CheckComboBox` and support multiple games.
If then there is still a demand for filter down to only 1 version, there could be a second step and replace it by a normal `ComboBox`.
This will allow the user to have all the power/funtionality he wants.

**Comment by StingMcRay** [comment]
I like to have 'All Version' for my self as i still add layouts on all versions i play, besides that, when i make a new preset file i like to test and look ad 'All Versions' :)

**Comment by auipga** [comment]
Just an idea: can `CheckComboBox` handle a right click and then act like radio buttons? I mean "select only this and deselect all others".

**Comment by auipga** [comment]
When will there be a new release containing this feature?
