### ISSUE TITLE
Rotation -> Copy function keeping object on mouse

### ISSUE THREAD

**Issue by StingMcRay** [AgmasGold/anno-designer#135]
According different tests i have pinpoint the copy/rotation bug (i hope)
When you selecting multiple objects and copy that (with the middle mouse button) the objects will be acting as intending, copy -> rotate & place -> cancel selection 

When you have only 1 object selected to rotate (middle mouse button), it will copy the object and keep it on the mouse, and will not clear when canceling, This should only be the function Rotate, as when we double click on an single object we copy that object.
![afbeelding](https://user-images.githubusercontent.com/18048706/63435079-8cb53d00-c426-11e9-860c-86076fee420e.png)

Hope we can tackle this one 

(Edit : On further tests is was the Move Function and trying to rotate)

**Comment by FroggieFrog** [comment]
Just to add some information from a chat on discord:

The issue with an object hanging at the cursor appears if you left click and hold the left mouse button while clicking the middle mouse button (or the R key).
