### ISSUE TITLE
optimize bundled images with zopfliPng

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#140]
If we optimize the bundled *.png files with [zopfliPng](https://github.com/google/zopfli) we could reduce the overall download size by ~2MB.
[The binary I used](https://github.com/imagemin/zopflipng-bin/tree/master/vendor/win32)

The parameters I tested with:
`zopflipng.exe -m -y --iterations=500 "path\to\AnnoDesigner\icons\*.png"`

Additional information:
The png format uses a DEFLATE algorithm and zopfli is a new/better implementation.
No data is lost. All applications that support png files can still view the optimized files because it is still the DEFLATE algorithm.
So just a smaller bundle to download. 🎉

**Comment by StingMcRay** [comment]
Go head every byte we slink the app is better :D
