### ISSUE TITLE
add option to zip all log files

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#152]
Maybe it is usefull to add an option to zip all log files.
This would make it easier for users to provide information for the developers if there is an issue.

**Comment by AgmasGold** [comment]
I'm not sure if this is something that would really fit with the designer. I realise we already have the libs in there for the auto update stuff, but even so, it feels like it would be a bit of a random feature to have just stuck in there. It might just clutter the interface and be one more thing we'd need to see in the codebase.

**Comment by FroggieFrog** [comment]
I thought it could fit in the `Help` menu and when there is an issue with the Designer they could provide the log files via `Discord` or an issue on `Github`.
If it does not seem necessary, go ahead and close the issue 😄

**Comment by AgmasGold** [comment]
Closing.

**Comment by FroggieFrog** [comment]
😢
