### ISSUE TITLE
Add frequently used road bar into default set.

### ISSUE THREAD

**Issue by Tomohiko-Mukai-aka-EiranKisotsu** [AgmasGold/anno-designer#154]
as one of user of Anno Designer,
i want you to add some road bar into default set into "Road tile" category.

Below are my (and peoples) most frequently used items.
・Small Road bar = 1x3. 
・Medium Road bar = 1x6.

・Small Road bar with intersection = 1x4
・Medium Road bar with intersection = 1x7
i Hope, someone read this request from an Anno Designer user.

**Comment by StingMcRay** [comment]
I will look into that, but i'm afraid it will end up in a menu like 
* Road bars > (the different road bars)

**Comment by FroggieFrog** [comment]
@Tomohiko-Mukai-aka-EiranKisotsu 
To clarify it a bit more (at least for me): Could you add some images? What do you mean with itersection?

Maybe there could also be presets for already rotated road bars.
Like "Road bar" _(Is this the correct wording?)_ and "Road bar (90°)".

@StingMcRay 
What is the reason to **not** put in the presets and "hide" it in a menu?

**Comment by StingMcRay** [comment]
well, @FroggieFrog, as he roads goes for all anno's i was planning to set the menu beneath the 'Bordellos road tile' in the "Road Bars" (as menu with the 4 new road bars) 
So this will be shown with the selected anno games

**Comment by FroggieFrog** [comment]
Ah ok, now I know what you mean. You mean a new "category" inside the presets tree. I thought you meant the application menu at the top.
So I think it would be cool to investigate the most common "road bars"/"road blocks" in the different games and add those to the presets.
Maybe the dimensions (of the buildings) differ from game to game. I don't know that from the top of my head.

**Comment by StingMcRay** [comment]
All Houses (the most used in a city layout) are always 3x3, whatever anno you pick

As example from what he means is this (explanation below the picture)
![afbeelding](https://user-images.githubusercontent.com/18048706/70605069-12d5d900-1bfa-11ea-9d62-3a495eb33821.png)
The red box contains 4 times the Medium Road bar with intersection = 1x7
The red arrow is the same one
The green arrow is a Great Road bar with 2 intersection = 1x8
And the blue arrow is the the Small Road bar with intersection = 1x4

The normal gray roads are the small 1x3 road bars

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
Sorry, was editting .json files by myself.
and made some of colorful road sets. 
This is what i want.
https://imgur.com/Ragd5TN

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
Below is what i want . ( the road sets)
![AnnoDesigner-RoadSets01](https://user-images.githubusercontent.com/58755230/70613391-e21e8f80-1c4b-11ea-9d58-851db7f9ed18.png)

Below is some of my layout without Road painted.
i am lazy to paint road.  (But since now, with above road sets, i could put roads.)
![anno-designer001](https://user-images.githubusercontent.com/58755230/70613390-e21e8f80-1c4b-11ea-97d0-1d85742c5999.png)

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
> All Houses (the most used in a city layout) are always 3x3, whatever anno you pick
> 
> As example from what he means is this (explanation below the picture)
> ![afbeelding](https://user-images.githubusercontent.com/18048706/70605069-12d5d900-1bfa-11ea-9d62-3a495eb33821.png)
> The red box contains 4 times the Medium Road bar with intersection = 1x7
> The red arrow is the same one
> The green arrow is a Great Road bar with 2 intersection = 1x8
> And the blue arrow is the the Small Road bar with intersection = 1x4
> 
> The normal gray roads are the small 1x3 road bars

Thanks !! this is what i want to say.

**Comment by StingMcRay** [comment]
Well, that looks nice, however : you can always choice a color after choices the road.
So, i will (try to) make the gray roads only (till 1x12) so hope that is not an problem then

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
> Well, that looks nice, however : you can always choice a color after choices the road.
> So, i will (try to) make the gray roads only (till 1x12) so hope that is not an problem then

Yep,  what sad is ... it didn't save the config. 
Everyday i  start the Anno Designer, always i need to configure Road Tiles.
it was frustrating. That is why Today, i editted .json file for Length Road sets.
For basic house length of {3,6,9}
For basic farm fields  length of {4,8,12}, {5,10,15}
and some important prime numbers , {7,11,13,17}. it help a lot.

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
> @Tomohiko-Mukai-aka-EiranKisotsu
> To clarify it a bit more (at least for me): Could you add some images? What do you mean with itersection?
> 
> Maybe there could also be presets for already rotated road bars.
> Like "Road bar" _(Is this the correct wording?)_ and "Road bar (90°)".
> 
> @StingMcRay
> What is the reason to **not** put in the presets and "hide" it in a menu?

Thanks for reading this thread. and sorry for my English, (the word "Road Bar").
Look at above image on my post.
i editted .json files, and trial and error, now custom preset with good road sets.
they are colorful and has good length of important prime numbers.
i just want you all to this road set built-in as default into [Road Category].
with variant Length.
MUST HAVE length is...
For basic house length of {3,6,9}
For basic farm fields length of {4,8,12} or {5,10,15}
 and some important prime numbers. {7, 11, 13 and 17}. 
it will help a lot to calculate our layout and save time.

**Comment by StingMcRay** [comment]
Well, just an menu idea from here : 
```
Road tile
Borderless road tile
> Road Bars  
   > Basic City 
       Road 1x3
       Road 1x6
       Road 1x9
   > Basic Farm
       Road 1x4
       Road 1x5
       Road 1x8
       (etc)
   > Road Measuring
       Road 1x7
       Road 1x11
       (etc)
```
Is this what you like then ?

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
> Well, just an menu idea from here :
> 
> ```
> Road tile
> Borderless road tile
> > Road Bars  
>    > Basic City 
>        Road 1x3
>        Road 1x6
>        Road 1x9
>    > Basic Farm / Intersection
>        Road 1x4
>        Road 1x5
>        Road 1x8
>        (etc)
>    > Road Measuring
>        Road 1x7
>        Road 1x11
>        (etc)
> > (A4) Anno 1404
> ```
> 
> _the anno version can be different, and the first two already exists_
> Is this what you like then ?
Year, it looks really cool, if it would built-in preset as default.
 i want you add one more important category.
Next to "Road Bars", add "Road Bars (Colorful)".

Below is what i want as default Preset...
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
●Road tile
● Borderless road tile
● Road Bars (Reguler)
    ・ Prime Num 3
       Road 1x3... ( and so on)
●Road Bars (Colorful)
     ・Num 3 (Green) // 3 is Prime Number
       Road 1x3
       Road 1x6
       Road 1x9
     ・Num 4 (Red) // 4 is Demi-Prime Number in practical layouting.
       Road 1x4
       Road 1x8
       Road 1x12
     > Num 5 (Blue) // 5 is Prime Num
       Road 1x5
       Road 1x10
     > Other Primes (Grey) // Some of important Prime Numbers
       Road 1x11
       Road 1x13
       Road 1x17

↑↑↑↑↑↑↑↑↑↑↑
That is all.  up to length of 17. 
it is enough for default "Preset".
Because the biggest public building (in Anno) has width of 17.
(if i remember correctly).

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
Thanks and sorry for reading my bad English.
 and the word "Demi-Prime number".
i don't know what is it called in English ? 
4 is ... Not prime number,  but is very Prime in layouting.

**Comment by StingMcRay** [comment]
I understand that you want colors, but that will not go, if i give a road a preset color, all roads will get that color so, the prime color of roads stay on the gray hand, if you want to give the road an other color, you will have to set the color after selecting a road peace.
*as i said before*

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
> I understand that you want colors, but that will not go, if i give a road a preset color, all roads will get that color so, the prime color of roads stay on the gray hand, if you want to give the road an other color, you will have to set the color after selecting a road peace.
> _as i said before_
Sure. 
But this application could give us "better preset file" 
and an option "Save the user_preset".
The point is... 
Users have to set the color, everytime he start the application.
(Like editing keybinding on a video game everytime you play...).
i know old age of "Anno Designer" at 2013.
At that age, the preset (.json or .cfg or something ?) file
was really small and easy  to Read and Edit for me.
i never say make it back to small old one.
...............Just give us "better preset file" and an option "Save the user_preset".
imho,  it should be on higher priority than localizing.

**Comment by StingMcRay** [comment]
An small roads menu is created in the new version
This is only available on standard color (you can change whenever you like) and Borderless (also you can switch this off)
If you switch on or both options, place the road always with the "Place Building" button.
![afbeelding](https://user-images.githubusercontent.com/18048706/70908813-700fc700-200c-11ea-9339-d2aa82042606.png)
