### ISSUE TITLE
Missing Numbers on Farm Buildings and Fields

### ISSUE THREAD

**Issue by StingMcRay** [AgmasGold/anno-designer#155]
This issue is noted for Anno 1800 Farm Buildings and Farm Fields, and will be fixed in the next Presets.json version (3.2.9)

**Comment by Tomohiko-Mukai-aka-EiranKisotsu** [comment]
i wonder.
in future. is there any chance Anno Designer have an option 
to save custom preset.json file.

**Comment by FroggieFrog** [comment]
@Tomohiko-Mukai-aka-EiranKisotsu
I created a separate issue for that (#158).

**Comment by StingMcRay** [comment]
This will be fixed in preset 3.2.9 coming with the new Anno Designer 8.5
