### ISSUE TITLE
Christmas icons

### ISSUE THREAD

**Issue by NiHoel** [AgmasGold/anno-designer#156]
[Christmas.zip](https://github.com/AgmasGold/anno-designer/files/3964326/Christmas.zip)

Found in data\ui\2kimages\main\3dicons\ornaments

**Comment by StingMcRay** [comment]
Thanks @NiHoel for the file, 
But i was aware of the missing ones, and i already add them to the icons, but the update still need make his way to here as i'm still busy to fix the new preset for that DLC and The Passage DLC

**Comment by NiHoel** [comment]
Didn't take much time for me to bundle them up, nor am I waiting for the Anno Designer.
