### ISSUE TITLE
move statistics from canvas

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#16]
I think it is better to move the statistics out of the canvas and display them on a separate panel beside the canvas.
The text for the statistics don't change at every frame and so there is no need to paint them on every frame.

Maybe a separate DockPanel like the other one. this Dockpanel could contain many TextBlocks in some GroupBoxes.
This should improve performance when simply moving the mouse.

**Comment by FroggieFrog** [comment]
I just wanted to say that I'm actually at work to fix this issue.
Follow progress at branch: [FroggieFrog\separate-statistics](https://github.com/FroggieFrog/anno-designer/tree/separate-statistics)

**Comment by AgmasGold** [comment]
fixed in #23
