### ISSUE TITLE
[1800] InfluenceRadius differs

### ISSUE THREAD

**Issue by auipga** [AgmasGold/anno-designer#3]
In Anno 1800 there is no **influence radius** but a **distance**.

Distances on **paved streets**:
- 49 Marketplace
- 41 Pub
- 32 Police
- 56 Church
- 49 School
- 48 Fire Station
- 56 Variety Theatre
- ? Bank
- ? Boxing Arena
- ? Hospital
- ? Members Club
- ? University

There are still some buildings with **radius**:
- Town Hall
- Trade Union
- Harbour buildings like Harbourmaster's, Cannons and Guns
- and more

Here is a example building with an InfluenceDistance of 10:
![InfluenceDistance](https://i.imgur.com/u12D68Z.jpg)

The building (e.g. residence) you want to be supported by the other building (e.g. marketplace) must overlap at least with one last tile of the influenced street. Lights colored houses are ok, dark is out of range.
![house-example](https://i.imgur.com/JtZuQlv.jpg)

**Comment by StingMcRay** [comment]
As that system is Street Depending, i can not make this system into the preset range (yet), i still looking into this so, give us some time to check if this is possible or not.

**Comment by AgmasGold** [comment]
I've added this idea to the Feature Ideas Project board. This would represent a significant amount of development - so not something we can get done straight away.

**Comment by StingMcRay** [comment]
Just a question from my site, when or if we can get this stuff build-in, would you choice to count all the green (and light green) , or just the dark green, as that has 100% for filled the inhabitants needs of that building? 
if you choice the last one, then the numbers you are providing here, are  not correct (maybe you can do it this way : ex: Marketplace Max% 32, min% 49)
For now i still looking for the numbers in the data file

**Comment by auipga** [comment]
@StingMcRay I counted the 100%-distance. (Try again with paved streets ;))
@AgmasGold I thought it would take some more effort. But there is a kinda dirty calculation:
**for each block** in a building { draw(square with edge length of sqrt( (x/2)^2 + (x/2)^2 ).rotate(45) }
then overlap/combine all shapes.

**Comment by AgmasGold** [comment]
Doing all those extra calls, and combining could be one way of doing it, yes. If we do manage to find the data, it might be that we implement the "dirty" solution, and see what it's performance is like.

**Comment by AgmasGold** [comment]
Feature in development: see branch at [https://github.com/AgmasGold/anno-designer/tree/InfluenceRangeDevelopment](https://github.com/AgmasGold/anno-designer/tree/InfluenceRangeDevelopment)

**Comment by StingMcRay** [comment]
Anno Designer and the Preset Parser no made to get thus numbers
sorry that it took a while to get the right numbers, but its now build in for the next version,
Some screens:
Dirt Street/Road
![afbeelding](https://user-images.githubusercontent.com/18048706/57787020-e8d83900-7734-11e9-8800-d34c91a78a98.png)
Paved Street Selected
![afbeelding](https://user-images.githubusercontent.com/18048706/57787056-fc839f80-7734-11e9-9116-59e17aff59ab.png)
The number is calculated as the data numbers comes as Dirt Road Distance.

Hope this will solve this issue as total

**Comment by auipga** [comment]
Thanks!!
