### ISSUE TITLE
add filter/search box for presets

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#31]
It would be nice to add a search box above the tree with the presets.
Then one could enter e.g. "ware" and the treeview is displaying all buildings which contain the search string e.g. "Warehouse".
This eliminates some clicking in the treeview.

**Comment by StingMcRay** [comment]
Can you please join our Discord https://discord.gg/m4fvSx

**Comment by StingMcRay** [comment]
i will make a start today / tomorrow with the search for preset list *03/04 may 2019*
