### ISSUE TITLE
What is the use of "Template" in presets.json?

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#36]
I looked at the "presets.json" file and found the "Template" node. But I could not find any use of this node.
What is/was the purpose of this node?

**Comment by StingMcRay** [comment]
I use the template name for checkers

**Comment by FroggieFrog** [comment]
@StingMcRay
Is there a list of all available values for "Template"?
Or are those values come straight from the extracted asset files?

I'm trying to get my head around predefined colors for templates and a list of all templates would be beneficial. I also could create a list by my own if it is necessary.

**Comment by StingMcRay** [comment]
No, the is not (yet) a Template List, except thus that are in the preset.json file are place (indeed by extracting the data from the anno rda files) es example : 
```

		{
			"Header": "(A4) Anno 1404",
			"Faction": "PlayerBuildings",
			"Group": "Residence",
			"Identifier": "PeasantHouse",
			"IconFileName": "A4_icon_116_132.png",
			"BuildBlocker": {
				"x": 3,
				"z": 3
			},
			"Template": "ResidenceBuilding",
			"InfluenceRange": 0,
			"InfluenceRadius": 0,
			"Localization": {
				"eng": "Peasant house",
				"ger": "Bauernhaus",
				"pol": "Chata wieśniaka",
				"rus": "Крестьянский дом"
			}
		},

```
But i can try to make you a list, but then what you need ? Building "Eng" Name and or Identifier *and ofc the Template Name*?

Regards

**Comment by FroggieFrog** [comment]
Ok, thank you for the information.
I will create a list out of presets.json.

My plan is to map a template to a specific color by default. So the user can still change the color, but for those who don't there will be gray roads, blue residences and so on.
The identifier doesn't matter in this case and the template is the least common denominator.

**Comment by StingMcRay** [comment]
Oke, Probably you need to enable the code in the MainWindows.cs to use that *colors.json*
and it it possible to set multiple template names (or 'Target Names') under a color definition ? 
If you not have a colors.json file i have an AD v7 one on my pc, as we not deliver it anymore sins 8.1
