### ISSUE TITLE
add default color to buildings

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#37]
I think it would be beneficial to add some default colors to the buildings.
So right from the get go all roads could be gray and all warehouses could be blue and so on.

This would add some continuity to the exported screenshots and remove some hassle from the user.

**Comment by StingMcRay** [comment]
In the past we used the color.json to pinpoint colors to that, we are still looking into that to see of we can use it again

**Comment by StingMcRay** [comment]
Further info : Because the original creator of this application has removed the use of that *asfare i know* because of the variety of anno's and different names where he build it on

**Comment by AgmasGold** [comment]
It was disabled for the intial re-release, there's some code in MainWindow.xaml.cs that loads a colors.json file.  In theory we can use it to create themes - one of which could be a default theme with different building colors.

**Comment by FroggieFrog** [comment]
These are some of my thoughts so far:
- What would be the advantage of supporting multiple predefined themes?
- How would you display multiple themes in the (current) color picker?
- A (simple) approach would be to map the already existing "Template" names form presets.json to a (list of) color(s).
- The current color picker supports 1 set of predefined colors [(StandardColors)](https://github.com/xceedsoftware/wpftoolkit/wiki/ColorPicker). I think this would be the perfect place for this.
- When a "Template" is mapped to multiple colors, use the first one by default.
- (not sure about this) When no color is found in the mapping, then use transparent. -> Breaking behaviour
Old: use the currently/previously selected color
- Change color of buildings in saved layouts, when mapping changed?
Example: layout.ad contains building with "Template:Residence" and "Color:blue", but the mapping changed to "Template:Residence" and "Color:yellow"

**Comment by StingMcRay** [comment]
Predefined colors are added for buildings in Anno Designer 8.4
