### ISSUE TITLE
NullReference exception on search and language change

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#48]
Steps to reproduce:
- App has language english
- Type "potato" in search field
- Change language to german
- Try to delete the search term -> exception

This also applies if you clear the search field before the language change.
- App has language english
- Type "potato" in search field
- Clear search field
- Change language to german
- Try to search for "Kartoffel" -> exception on first character

**Comment by AgmasGold** [comment]
fixed by #49
