### ISSUE TITLE
allow to change color of already placed object

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#55]
issue migrated from [https://github.com/JcBernack/anno-designer/issues/22](https://github.com/JcBernack/anno-designer/issues/22) point 2

- Add context menu for objects on canvas?
- Add "pipette" (color chooser) tool and then click on building?
- Add option to change color to a predefined one? (see issue #37)

**Comment by StingMcRay** [comment]
1: My opinion on that : 
    A: no, because the app has the stats *UN-selected* so ppl see whats on the canvas, and 
    B: the preset menu is already there, no need for more object menu's
2: That's would be a nice idea, however (also told in #45) if we click on an object the color will be set
3: Yes : would very nice idea, because normally we need to delete object, pick the right color again and then place object back on canvas

**Comment by AgmasGold** [comment]
fixed in #58
