### ISSUE TITLE
How to Fix this Crash

### ISSUE THREAD

**Issue by crashslider** [AgmasGold/anno-designer#59]
Does not start, shows this error

![error](https://user-images.githubusercontent.com/4461489/57303371-2bea3a80-70ab-11e9-9ef2-f80fb969e4f2.JPG)

error-log
`*** TreeView SetTreeViewState Error *** 2019-05-07 

Message: El índice estaba fuera del intervalo. Debe ser un valor no negativo e inferior al tamaño de la colección.
Nombre del parámetro: index 
 Stack Trace:
   en System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   en AnnoDesigner.TreeViewExtensions.SetState(TreeViewItem t, List`1 nodeStateList, Int32 currentIndex)
   en AnnoDesigner.TreeViewExtensions.SetState(TreeViewItem t, List`1 nodeStateList, Int32 currentIndex)
   en AnnoDesigner.TreeViewExtensions.SetTreeViewState(TreeView t, List`1 nodeStateList)
   en AnnoDesigner.MainWindow.WindowLoaded(Object sender, RoutedEventArgs e)

*** Application Unhandled Error *** 2019-05-07 

Message: El valor de la propiedad 'MaxTextHeight' debe ser mayor que cero.
Nombre del parámetro: value 
 Stack Trace:
   en System.Windows.Media.FormattedText.set_MaxTextHeight(Double value)
   en AnnoDesigner.AnnoCanvas.RenderStatistics(DrawingContext drawingContext)
   en AnnoDesigner.AnnoCanvas.OnRender(DrawingContext drawingContext)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en MS.Internal.Helper.ArrangeElementWithSingleChild(UIElement element, Size arrangeSize)
   en System.Windows.Controls.ContentPresenter.ArrangeOverride(Size arrangeSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Documents.AdornerDecorator.ArrangeOverride(Size finalSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Window.ArrangeOverride(Size arrangeBounds)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Interop.HwndSource.SetLayoutSize()
   en System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   en System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   en System.Windows.Window.SetRootVisual()
   en System.Windows.Window.SetRootVisualAndUpdateSTC()
   en System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   en System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   en System.Windows.Window.CreateSourceWindowDuringShow()
   en System.Windows.Window.SafeCreateWindowDuringShow()
   en System.Windows.Window.ShowHelper(Object booleanBox)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

*** Application Unhandled Error *** 2019-05-07 

Message: El valor de la propiedad 'MaxTextHeight' debe ser mayor que cero.
Nombre del parámetro: value 
 Stack Trace:
   en System.Windows.Media.FormattedText.set_MaxTextHeight(Double value)
   en AnnoDesigner.AnnoCanvas.RenderStatistics(DrawingContext drawingContext)
   en AnnoDesigner.AnnoCanvas.OnRender(DrawingContext drawingContext)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en MS.Internal.Helper.ArrangeElementWithSingleChild(UIElement element, Size arrangeSize)
   en System.Windows.Controls.ContentPresenter.ArrangeOverride(Size arrangeSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Documents.AdornerDecorator.ArrangeOverride(Size finalSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Controls.Border.ArrangeOverride(Size finalSize)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Window.ArrangeOverride(Size arrangeBounds)
   en System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   en System.Windows.UIElement.Arrange(Rect finalRect)
   en System.Windows.Interop.HwndSource.SetLayoutSize()
   en System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   en System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   en System.Windows.Window.SetRootVisual()
   en System.Windows.Window.SetRootVisualAndUpdateSTC()
   en System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   en System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   en System.Windows.Window.CreateSourceWindowDuringShow()
   en System.Windows.Window.SafeCreateWindowDuringShow()
   en System.Windows.Window.ShowHelper(Object booleanBox)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.DispatcherOperation.InvokeImpl()
   en System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Windows.Threading.DispatcherOperation.Invoke()
   en System.Windows.Threading.Dispatcher.ProcessQueue()
   en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   en System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   en System.Windows.Application.RunDispatcher(Object ignore)
   en System.Windows.Application.RunInternal(Window window)
   en System.Windows.Application.Run(Window window)
   en AnnoDesigner.App.Main()

`

**Comment by StingMcRay** [comment]
Spanish:
El mensaje "Failed to restore previous preset menu" no es otra cosa que la de que el programa puede restaurar el viejo 'State' que está guardado al salir. Me gusta saber si el programa que sigue en marcha después de este mensaje
Sin embargo, investigaremos este error:

English:
The message "Failed to restore previous preset menu" is nothing else then that the program can restore the old 'State' that is saved on quit. I like to know if the program still running after this message
However we will look into this error:

```
Message: The index was out of range. It must be a non-negative value and smaller than the size of the collection.
Parameter name: index....
```

**Comment by StingMcRay** [comment]
. también..: Con la versión que tiene y el archivo de preajuste que utiliza (puede ver esto en el menú'Ayuda')

Also : With version do you have and witch preset file do you use  (you can see this on the 'Help' menu)

**Comment by crashslider** [comment]
The program does not start, shows the following and close.
![error](https://user-images.githubusercontent.com/4461489/57310570-06aff900-70b8-11e9-8e4c-07f82d5a09bd.JPG)
Presets File v3.1.1

**Comment by StingMcRay** [comment]
Spanish:
Si selecciona Anno Designer Folder, habrá un número de versión adjunto en el nombre de la carpeta, como'Anno Designer v8.2'.
![afbeelding](https://user-images.githubusercontent.com/18048706/57310903-ec434300-70ea-11e9-9aaa-d2f0baf07de4.png)
Si se trata de una versión anterior a la 8.2, pruebe primero la versión más reciente desde aquí..: 
https://github.com/AgmasGold/anno-designer/tree/AnnoDesignerV8.2
y descargue la actualización de presets v3.1.1 de nuevo aquí:
https://github.com/AgmasGold/anno-designer/releases/tag/Presetsv3.1.1

English:
If you check you Anno Designer Folder, there would be a Version Number attached in folder name, like 'Anno Designer v8.2'
![afbeelding](https://user-images.githubusercontent.com/18048706/57310903-ec434300-70ea-11e9-9aaa-d2f0baf07de4.png)
If this is an older version then 8.2, then try first the newest version from here : 
https://github.com/AgmasGold/anno-designer/tree/AnnoDesignerV8.2
and download the Preset Update v3.1.1 again here:
https://github.com/AgmasGold/anno-designer/releases/tag/Presetsv3.1.1

**Comment by crashslider** [comment]
Delete al files and download Anno Designer v8.2 and  Preset File V3.1.1 
same problem

![anno](https://user-images.githubusercontent.com/4461489/57311878-78894200-70ba-11e9-82d0-cd7d20eb2a07.JPG)

**Comment by StingMcRay** [comment]
Lo investigaremos entonces.

We will look into it then

**Comment by AgmasGold** [comment]
Hi crashslider,

It looks like the settings might be in an incorrect state. There is a folder in `[YOUR_USERNAME\AppData\Local\AnnoDesigner `. Could you try deleting the AnnoDesigner folder and re-open the app.

**Comment by crashslider** [comment]
Perfect! problem fix
Thank.
