### ISSUE TITLE
2205 modules appearing in 2070 section of the menu

### ISSUE THREAD

**Issue by AgmasGold** [AgmasGold/anno-designer#80]
It looks like some 2205 modules are appearing in the 2070 section of the menu. When placed, they appear as Uknown Object. Probably a bug in `BuildingPresets.AddToTreeView()`.

![image](https://user-images.githubusercontent.com/48861520/57804994-e6d1a280-7753-11e9-9ea2-2a5f62dd0731.png)

**Comment by StingMcRay** [comment]
Odd, but i will dive into that tomorrow then

**Comment by StingMcRay** [comment]
currently awaiting completion of PR #81
